### ISSUE TITLE
Pictures?

### ISSUE THREAD

**Issue by Matthww** [DevLodge/Logger#2]
Is it possible to let the bot upload pictures if they get deleted?

**Comment by LWTechGaming** [comment]
When a message only contains an embed, be it image or an `embed` object, `message.content` is an empty string. When the message is deleted, only the content is provided in the event. So in conclusion, it's not possible due to API limitations.

**Comment by Matthww** [comment]
Oh well that sucks

**Comment by LWTechGaming** [comment]
Addendum to my last, it would be possible by iterating through the `embeds` parameter of the message but I'm not sure if it's worth implementing. If we decide to do this it's a non-essential feature, we have more pressing matters right now 😄

**Comment by caf203** [comment]
I'm closing this issue: attachments can't be used when they get deleted. You get "cannot access discord.storage" or something.
